[package]
name = "newtons-fractal"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = {version = "0.35.1", features = ["bundled", "unsafe_textures"]}
sdl2-sys = "0.35.1"
